name: BreakReplace
main: BreakReplace\Main
version: 1.0.0
api: 2.0.0
author: MCPEPIG

permissions:
 breakreplace:
  default: op
  description: "Allows using all BreakReplace features" 
  children:
    breakreplace.command:
      default: op
      description: "Allow using allBreakReplace commands"
      children:
        breakreplace.command.breakreplace:
          default: op
          description: "Allow using /breakreplace"
